In [1]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [2]:
data = pd.read_csv("./weight_height_10000.csv")
data

Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9991  Female  66.172652  136.777454
9992  Female  67.067155  170.867906
9993  Female  63.867992  128.475319
9994  Female  69.034243  163.852461
9995  Female  61.944246  113.649103

[9996 rows x 3 columns]

In [3]:
X = data.loc[:, "Height":].to_numpy()
y = pd.get_dummies(data.Gender, prefix='Gender').to_numpy()[:, 1] # 1 -> male, 0 -> female
print(X, X.shape)
print(y, y.shape)
y

[[ 73.84701702 241.89356318]
 [ 68.78190405 162.31047252]
 [ 74.11010539 212.74085556]
 ...
 [ 63.86799221 128.47531878]
 [ 69.03424313 163.85246135]
 [ 61.94424588 113.64910268]] (9996, 2)
[1 1 1 ... 0 0 0] (9996,)


array([1, 1, 1, ..., 0, 0, 0], dtype=uint8)

In [4]:
# 2
max_x = np.max(X, axis=0)
min_x = np.min(X, axis=0)

X_01 = (X - min_x)/(max_x - min_x)
X_01

array([[0.79172838, 0.863139  ],
       [0.58695829, 0.4754764 ],
       [0.8023644 , 0.72113127],
       ...,
       [0.38830089, 0.31065968],
       [0.59715974, 0.48298768],
       [0.31052854, 0.23843869]])

In [75]:
# 3
X_train, X_test, y_train, y_test = train_test_split(X_01, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((7996, 2), (2000, 2), (7996,), (2000,))

In [80]:
# 4
clf = LogisticRegression(random_state=0).fit(X_train, y_train)

In [84]:
print(clf.coef_, clf.intercept_)


[[-0.84560251 22.20298289]] [-10.04432641]


In [88]:
print(clf.predict(X_test[:1]))
print(y_test[:1])

[1]
[1]


In [11]:
# 5

N = X_train.shape[0] # 100
indices = np.random.permutation(N)
X_train = X_train[indices]
y_train = y_train[indices]

intercept = np.ones((X_train.shape[0], 1))
X_b = np.concatenate((intercept, X_train), axis=1)

print('X_b', X_b.shape)
print('y_train', y_train.shape)
print('N', N)

X_b (7996, 3)
y_train (7996,)
N 7996


In [12]:
def sigmoid_function(z):
    return 1 / (1 + np.exp(-z))

def loss_function(y_hat, y):
    return (-y*np.log(y_hat) - (1 - y)*np.log(1 - y_hat))

def predict(x, theta):    
    z = np.dot(x, theta)
    y_hat = sigmoid_function(z)
    
    return y_hat

In [14]:
lr = 0.01
num_iter = 100

theta = np.random.rand(3,)

losses = []
preds   = []
accuracies = []

y_hats = []
for epoch in range(num_iter):
    for i in range(0, N):
        xi = X_b[i:i+1]
        yi = y_train[i:i+1]
        
        # compute output
        y_hat = predict(xi, theta)
        # compute loss
        loss = loss_function(y_hat, yi)
        # compute mean of gradient
        gradient = np.dot(xi.T, (y_hat - yi))

        # update
        theta = theta - lr*gradient  

    losses.append(loss)  
        

In [ ]:
theta

array([-11.38581613,  -3.31591334,  27.71041255])

In [15]:
# compute acc
preds = []
for i in range(0, N):
    xi = X_b[i:i+1]
    yi = y_train[i:i+1]
    
    y_hat = predict(xi, theta).round()    
    preds.append(y_hat[0])

In [16]:
acc = (preds == y_train).mean()
print(acc)

0.9089544772386193


In [68]:
theta = np.random.rand(3,)
theta

array([0.70913919, 0.746606  , 0.75643976])